// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderItem represents an item within an order.
type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId   string  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName string  `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity    int32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice   float64 `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
}

func (x *OrderItem) Reset()         { *x = OrderItem{} }
func (x *OrderItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *OrderItem) ProtoMessage()  {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

// Order represents a complete order.
type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string       `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items     []*OrderItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total     float64      `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	Status    string       `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt string       `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string       `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Order) Reset()         { *x = Order{} }
func (x *Order) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *Order) ProtoMessage()  {}

func (x *Order) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateOrderRequest
type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string       `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items  []*OrderItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreateOrderRequest) Reset()         { *x = CreateOrderRequest{} }
func (x *CreateOrderRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CreateOrderRequest) ProtoMessage()  {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// CreateOrderResponse
type CreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order   *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateOrderResponse) Reset()         { *x = CreateOrderResponse{} }
func (x *CreateOrderResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CreateOrderResponse) ProtoMessage()  {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListOrdersRequest
type ListOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListOrdersRequest) Reset()         { *x = ListOrdersRequest{} }
func (x *ListOrdersRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ListOrdersRequest) ProtoMessage()  {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListOrdersResponse
type ListOrdersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *ListOrdersResponse) Reset()         { *x = ListOrdersResponse{} }
func (x *ListOrdersResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ListOrdersResponse) ProtoMessage()  {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

// UpdateOrderStatusRequest
type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId   string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatus string `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
}

func (x *UpdateOrderStatusRequest) Reset()         { *x = UpdateOrderStatusRequest{} }
func (x *UpdateOrderStatusRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *UpdateOrderStatusRequest) ProtoMessage()  {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

// UpdateOrderStatusResponse
type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order   *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateOrderStatusResponse) Reset()         { *x = UpdateOrderStatusResponse{} }
func (x *UpdateOrderStatusResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *UpdateOrderStatusResponse) ProtoMessage()  {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateOrderStatusResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *UpdateOrderStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateOrderStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetOrderRequest
type GetOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *GetOrderRequest) Reset()         { *x = GetOrderRequest{} }
func (x *GetOrderRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetOrderRequest) ProtoMessage()  {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// GetOrderResponse
type GetOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Found bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetOrderResponse) Reset()         { *x = GetOrderResponse{} }
func (x *GetOrderResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetOrderResponse) ProtoMessage()  {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var _ = reflect.TypeOf
var _ = sync.Mutex{}
