// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product represents a product in the catalog.
type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock       int32   `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Category    string  `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Product) Reset()         { *x = Product{} }
func (x *Product) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *Product) ProtoMessage()  {}

func (x *Product) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// GetProductRequest
type GetProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *GetProductRequest) Reset()         { *x = GetProductRequest{} }
func (x *GetProductRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetProductRequest) ProtoMessage()  {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// GetProductResponse
type GetProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Found   bool     `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetProductResponse) Reset()         { *x = GetProductResponse{} }
func (x *GetProductResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetProductResponse) ProtoMessage()  {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *GetProductResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ListProductsRequest
type ListProductsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *ListProductsRequest) Reset()         { *x = ListProductsRequest{} }
func (x *ListProductsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ListProductsRequest) ProtoMessage()  {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// ListProductsResponse
type ListProductsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ListProductsResponse) Reset()         { *x = ListProductsResponse{} }
func (x *ListProductsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ListProductsResponse) ProtoMessage()  {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// StockItem
type StockItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity  int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *StockItem) Reset()         { *x = StockItem{} }
func (x *StockItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *StockItem) ProtoMessage()  {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// CheckStockRequest
type CheckStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*StockItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CheckStockRequest) Reset()         { *x = CheckStockRequest{} }
func (x *CheckStockRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CheckStockRequest) ProtoMessage()  {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CheckStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// CheckStockResponse
type CheckStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available            bool     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UnavailableProducts  []string `protobuf:"bytes,3,rep,name=unavailable_products,json=unavailableProducts,proto3" json:"unavailable_products,omitempty"`
}

func (x *CheckStockResponse) Reset()         { *x = CheckStockResponse{} }
func (x *CheckStockResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CheckStockResponse) ProtoMessage()  {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CheckStockResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckStockResponse) GetUnavailableProducts() []string {
	if x != nil {
		return x.UnavailableProducts
	}
	return nil
}

// UpdateStockRequest
type UpdateStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId      string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	QuantityChange int32  `protobuf:"varint,2,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"`
}

func (x *UpdateStockRequest) Reset()         { *x = UpdateStockRequest{} }
func (x *UpdateStockRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *UpdateStockRequest) ProtoMessage()  {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

// UpdateStockResponse
type UpdateStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Success bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateStockResponse) Reset()         { *x = UpdateStockResponse{} }
func (x *UpdateStockResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *UpdateStockResponse) ProtoMessage()  {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateStockResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var _ = reflect.TypeOf
var _ = sync.Mutex{}
