// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/product/product.proto

package product

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// ProductService is the client API for ProductService service.
type ProductService interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...client.CallOption) (*GetProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...client.CallOption) (*ListProductsResponse, error)
	CheckStock(ctx context.Context, in *CheckStockRequest, opts ...client.CallOption) (*CheckStockResponse, error)
	UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...client.CallOption) (*UpdateStockResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) GetProduct(ctx context.Context, in *GetProductRequest, opts ...client.CallOption) (*GetProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.GetProduct", in)
	out := new(GetProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...client.CallOption) (*ListProductsResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.ListProducts", in)
	out := new(ListProductsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) CheckStock(ctx context.Context, in *CheckStockRequest, opts ...client.CallOption) (*CheckStockResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.CheckStock", in)
	out := new(CheckStockResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...client.CallOption) (*UpdateStockResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.UpdateStock", in)
	out := new(UpdateStockResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceHandler is the server API for ProductService service.
type ProductServiceHandler interface {
	GetProduct(context.Context, *GetProductRequest, *GetProductResponse) error
	ListProducts(context.Context, *ListProductsRequest, *ListProductsResponse) error
	CheckStock(context.Context, *CheckStockRequest, *CheckStockResponse) error
	UpdateStock(context.Context, *UpdateStockRequest, *UpdateStockResponse) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) error {
	type productServiceHandler interface {
		GetProduct(ctx context.Context, in *GetProductRequest, out *GetProductResponse) error
		ListProducts(ctx context.Context, in *ListProductsRequest, out *ListProductsResponse) error
		CheckStock(ctx context.Context, in *CheckStockRequest, out *CheckStockResponse) error
		UpdateStock(ctx context.Context, in *UpdateStockRequest, out *UpdateStockResponse) error
	}
	type ProductService struct {
		productServiceHandler
	}
	h := &productServiceHandlerWrapper{hdlr}
	return s.Handle(s.NewHandler(&ProductService{h}, opts...))
}

type productServiceHandlerWrapper struct {
	ProductServiceHandler
}

func (h *productServiceHandlerWrapper) GetProduct(ctx context.Context, in *GetProductRequest, out *GetProductResponse) error {
	return h.ProductServiceHandler.GetProduct(ctx, in, out)
}

func (h *productServiceHandlerWrapper) ListProducts(ctx context.Context, in *ListProductsRequest, out *ListProductsResponse) error {
	return h.ProductServiceHandler.ListProducts(ctx, in, out)
}

func (h *productServiceHandlerWrapper) CheckStock(ctx context.Context, in *CheckStockRequest, out *CheckStockResponse) error {
	return h.ProductServiceHandler.CheckStock(ctx, in, out)
}

func (h *productServiceHandlerWrapper) UpdateStock(ctx context.Context, in *UpdateStockRequest, out *UpdateStockResponse) error {
	return h.ProductServiceHandler.UpdateStock(ctx, in, out)
}
